import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'
import NavBar from '@/components/NavBar/NavBar'
import Providers from './Providers'

export const metadata: Metadata = {
  title: 'Dungeons and Dragons application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <NavBar />
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  )
}
