import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'
import NavBar from '@/components/NavBar/NavBar'
import Providers from './Providers'
import { auth } from '@/lib/auth'

export const metadata: Metadata = {
  title: 'Dungeons and Dragons application',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  const session = await auth()
  return (
    <html lang='en'>
      <body>
        <Providers session={session}>
          <NavBar />
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  )
}
