import { Item } from '@/interfaces/Item'

const mockItem: Item = {
  id: '0',
  description: [
    'A sturdy wooden shield featuring intricate carvings. Provides excellent protection in battle.',
    'More info bla bla bla',
  ],
  link: 'example.com/wooden_shield',
  name: 'Wooden Shield',
  prize: '30 gold pieces',
  tags: ['Armor', 'Shield', 'Defensive'],
  type: 'Shield',
  weight: '6 lbs',
}

const mockItems: Item[] = [
  {
    id: '1',
    description: [
      'A finely crafted sword with an intricate hilt and a blade engulfed in eternal flames.',
    ],
    link: 'example.com/sword_of_eternal_flame',
    name: 'Sword of the Eternal Flame',
    prize: '800 gold',
    tags: ['Weapon', 'Magical', 'Fire', 'Melee'],
    type: 'Melee Weapon',
    weight: '4 lbs',
  },
  {
    id: '2',
    description: [
      'A small vial filled with shimmering red liquid. Restores moderate amount of health when consumed.',
    ],
    link: 'example.com/potion_of_healing',
    name: 'Potion of Healing',
    prize: '50 gold',
    tags: ['Consumable', 'Healing', 'Potion'],
    type: 'Consumable',
    weight: '0.5 lbs',
  },
  {
    id: '3',
    description: [
      'A lightweight cloak made from enchanted elven fabric. Grants invisibility when hood is pulled over the head.',
    ],
    link: 'example.com/elven_cloak_of_invisibility',
    name: 'Elven Cloak of Invisibility',
    prize: '1200 gold',
    tags: ['Clothing', 'Magical', 'Stealth'],
    type: 'Clothing',
    weight: '1 lb',
  },
  {
    id: '4',
    description: [
      'A polished amulet featuring a deep blue gemstone. Enhances wisdom and understanding.',
    ],
    link: 'example.com/amulet_of_wisdom',
    name: 'Amulet of Wisdom',
    prize: '450 gold',
    tags: ['Accessory', 'Magical', 'Wisdom'],
    type: 'Accessory',
    weight: '0.2 lbs',
  },
  {
    id: '5',
    description: [
      'A rolled-up parchment inscribed with arcane symbols. Cast Fireball spell upon reading.',
    ],
    link: 'example.com/scroll_of_fireball',
    name: 'Scroll of Fireball',
    prize: '150 gold',
    tags: ['Magical', 'Offensive', 'Scroll', 'Fire'],
    type: 'Scroll',
    weight: '0.1 lbs',
  },
  {
    id: '6',
    description: [
      "A pair of gauntlets crafted from enchanted steel. Channels the user's strength into powerful shockwaves.",
      'These gauntlets were forged in the heart of a volcano by a legendary blacksmith.',
    ],
    link: 'example.com/gauntlets_of_shockwaves',
    name: 'Gauntlets of Shockwaves',
    prize: '1200 gold',
    tags: ['Armor', 'Magical', 'Strength', 'Melee'],
    type: 'Armor',
    weight: '2.5 lbs',
  },
  {
    id: '7',
    description: [
      'A mysterious hourglass filled with shimmering sand. When activated, it can slow down time in a localized area.',
      'Legends say that the sand inside comes from the deserts of the God of Time.',
    ],
    link: 'example.com/hourglass_of_temporal_shift',
    name: 'Hourglass of Temporal Shift',
    prize: '2500 gold',
    tags: ['Magical', 'Time', 'Utility'],
    type: 'Artifact',
    weight: '3 lbs',
  },
  {
    id: '8',
    description: [
      "A set of enchanted throwing knives that always return to the owner's hand after being thrown.",
      'The blades are forged from a rare metal found only in the deepest caverns of the world.',
    ],
    link: 'example.com/returning_throwing_knives',
    name: 'Returning Throwing Knives',
    prize: '600 gold',
    tags: ['Weapon', 'Throwing', 'Precision'],
    type: 'Ranged Weapon',
    weight: '1 lb',
  },
  {
    id: '9',
    description: [
      'A crown adorned with glittering gemstones, said to grant the wearer control over the minds of others.',
      'Many have sought this crown for the power it promises, but few have proven worthy of it.',
    ],
    link: 'example.com/crown_of_domination',
    name: 'Crown of Domination',
    prize: '3500 gold',
    tags: ['Accessory', 'Mind Control', 'Magical'],
    type: 'Accessory',
    weight: '0.8 lbs',
  },
  {
    id: '10',
    description: [
      'A tome filled with forbidden knowledge, written in an ancient language incomprehensible to most.',
      'Reading even a few lines from this book can grant immense power, but at a great cost.',
      'The pages seem to shift and change, rewriting themselves as you read.',
    ],
    link: 'example.com/grimoire_of_eldritch_secrets',
    name: 'Grimoire of Eldritch Secrets',
    prize: '5000 gold',
    tags: ['Book', 'Dark Magic', 'Cursed'],
    type: 'Artifact',
    weight: '2.2 lbs',
  },
  {
    id: '11',
    description: [
      'A set of enchanted goggles that allow the wearer to see into the ethereal plane and interact with spirits.',
      'The lenses are made from the crystallized tears of a benevolent ghost.',
    ],
    link: 'example.com/ethereal_goggles',
    name: 'Ethereal Goggles',
    prize: '800 gold',
    tags: ['Magical', 'Spirits', 'Sight'],
    type: 'Accessory',
    weight: '0.5 lbs',
  },
  {
    id: '12',
    description: [
      'A staff carved from the heartwood of an ancient tree. It crackles with lightning and can summon thunderstorms.',
      'Legends say that the tree it came from was struck by lightning during a celestial event.',
    ],
    link: 'example.com/staff_of_thunder',
    name: 'Staff of Thunder',
    prize: '1800 gold',
    tags: ['Weapon', 'Magical', 'Lightning', 'Casting'],
    type: 'Staff',
    weight: '4.5 lbs',
  },
  {
    id: '13',
    description: [
      'A set of enchanted boots that allow the wearer to traverse any surface as if it were solid ground.',
      'These boots were a gift from a reclusive group of earth elementals.',
    ],
    link: 'example.com/boots_of_earthwalking',
    name: 'Boots of Earthwalking',
    prize: '950 gold',
    tags: ['Magical', 'Mobility', 'Earth'],
    type: 'Accessory',
    weight: '1.2 lbs',
  },
  {
    id: '14',
    description: [
      'A mysterious crystal orb that displays swirling patterns of color. Gazing into it reveals glimpses of distant places and times.',
      'Scholars speculate that it may be a portal to alternate dimensions.',
    ],
    link: 'example.com/crystal_oracle',
    name: 'Crystal Oracle',
    prize: '3000 gold',
    tags: ['Magical', 'Divination', 'Mystical'],
    type: 'Artifact',
    weight: '0.7 lbs',
  },
  {
    id: '15',
    description: [
      'A set of enchanted paintbrushes that bring paintings to life. Whatever is painted becomes a temporary, animated creation.',
      'The bristles are made from the feathers of a mythical phoenix.',
      'Each brush is attuned to a different element, allowing for a variety of effects.',
    ],
    link: "example.com/painter's_brushes",
    name: "Painter's Brushes",
    prize: '2200 gold',
    tags: ['Artistic', 'Magical', 'Creation'],
    type: 'Tool',
    weight: '0.4 lbs',
  },
]

export { mockItem, mockItems }
